name: nutri_calc
description: Flutter app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fluttertoast: ^7.1.6
  csv: ^4.1.0
  file_picker: ^3.0.0
  path_provider:
  pdf: ^1.3.24
  flutter_full_pdf_viewer: ^1.0.6
  flutter_pdfview: ^1.0.4
  syncfusion_flutter_pdfviewer:
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/data.csv
  fonts:
    - family: Josefin Sans
      fonts:
        - asset: assets/JosefinSans-Regular.ttf